name: Utility repo release
on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write
  pull-requests: read
  issues: write

jobs:
  check_image_on_amd64:
    runs-on: ubuntu-latest
    environment: common

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          tags: utility-test:linux-amd64
          platforms: linux/amd64

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest
        env:
          IMAGE_NAME: "utility-test:linux-amd64"
        run: |
          pytest

  check_image_on_arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          tags: utility-test:linux-arm64
          platforms: linux/arm64

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest
        env:
          IMAGE_NAME: "utility-test:linux-arm64"
        run: |
          pytest
  publish-production-image:
    runs-on: ubuntu-20.04
    needs: [check_image_on_amd64, check_image_on_arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push production Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ujjwalbharti111/utility:${{github.ref_name}},ujjwalbharti111/utility:latest
